### ISSUE TITLE
The Project.getConvention() method has been deprecated

### ISSUE THREAD

**Issue by ghost** [jfrog/artifactory-gradle-plugin#43]
### Describe the bug

When building on Gradle 8.2 I get the following warning

```
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
        at org.jfrog.gradle.plugin.artifactory.utils.ConventionUtils.getOrCreateArtifactoryConvention(ConventionUtils.java:28)
        at org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin.apply(ArtifactoryPlugin.java:27)
        at org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin.apply(ArtifactoryPlugin.java:17)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
```

`Project.getConvention()` is deprecated for removal in Gradle 9.0

### Current behavior

The Artifactory plugin in version 5.0.3 emits warnings about using deprecated Gradle features.

### Artifactory Gradle plugin version

5.0.3

### Operating system type and version

MacOS aarch64

### JFrog Artifactory version

N/A

### Gradle version

8.2.1

**Comment by bmuschko** [comment]
What's the way forward here? Is JFrog planning to fix the issue or would you rather want to receive a pull request?

**Comment by yahavi** [comment]
@bmuschko,
Thanks for reporting this issue.
We're more than happy to accept code contributions for this plugin.

**Comment by yahavi** [comment]
@ghost @bmuschko 
Version 5.1.10 of the Gradle Artifactory plugin has just been released. In this release, we've made the transition from Gradle conventions to extensions. If you'd like to, please consider upgrading, and we'd love to hear your feedback on this update.
